name: Lint and tests
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Project checkout
        uses: actions/checkout@v1
      - name: Node.js setup
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        uses: actions/setup-node@v1.1.0
      - name: Installation of dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: E2E tests
        run: npm run pretest:github && npm test